### ISSUE TITLE
nc_open Error in R_nc4_open: NetCDF: Access failure

### ISSUE THREAD

**Issue by nhill917** [BigelowLab/thredds#7]
Hi, I am trying to download ncdfs from the bran2020 database using thredds in R. (https://dapds00.nci.org.au/thredds/catalog/gb6/BRAN/BRAN2020/catalog.html) 

I have worked my way through the thredds vignette successfully but when I try to run the nc_open() command, it is unable to find the url created. Where do I source the base_uri from? It is not explained in the vignette (although i feel it should be simple). Or is it the correct url but there is another issue?

Here is a link to the nc file in particular - https://dapds00.nci.org.au/thredds/catalog/gb6/BRAN/BRAN2020/annual/catalog.html?dataset=gb6/BRAN/BRAN2020/annual/ocean_temp_ann_2004.nc

Thank you for any and all feedback.

library(thredds)
top_uri <- 'https://dapds00.nci.org.au/thredds/catalog/gb6/BRAN/BRAN2020/catalog.xml'
Top <- thredds::CatalogNode$new(top_uri, prefix = "thredds")
L3 <- Top$get_catalogs("annual")
sst <- L3[[1]]$get_datasets("ocean_temp_ann_2004.nc")

base_uri <- "https://dapds00.nci.org.au/thredds/ncss/grid/"
uri <- paste0(base_uri, sst[["ocean_temp_ann_2004.nc"]]$url)
NC <- ncdf4::nc_open(uri)

syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: Validation^ errors: No variables requested -- 
Error in R_nc4_open: NetCDF: Access failure
Error in ncdf4::nc_open(uri) : 
  Error in nc_open trying to open file https://dapds00.nci.org.au/thredds/ncss/grid/gb6/BRAN/BRAN2020/annual/ocean_temp_ann_2004.nc (return_on_error= FALSE )

If I use a slightly different url I get the error:
base_uri <- "https://dapds00.nci.org.au/thredds/catalog"
uri <- paste0(base_uri, sst[["ocean_temp_ann_2005.nc"]]$url)
NC <- ncdf4::nc_open(uri, verbose=T)

[1] "nc_open: entering, ncdf4 package version ncdf4_1.21_20230105 | underlying netcdf library version 4.9.2 of Oct 13 2023 17:35:17 $"
syntax error, unexpected WORD_WORD, expecting SCAN_ATTR or SCAN_DATASET or SCAN_ERROR
context: <html^ xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> <head> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"> <title>TDS - Error report</title> <link rel="stylesheet" href="/thredds/tds.css" type="text/css"/> </head> <body> <h1>HTTP Status 404 - Not Found</h1> <HR size="1" noshade="noshade"> <p><b>Status</b> 404 - Not Found</p> <HR size="1" noshade="noshade"> <h3>THREDDS Data Server Version 4.6 -- <a href='https://www.unidata.ucar.edu/software/thredds/v4.6/tds/TDS.html'>Documentation</a></h3> </body></html>
Error in R_nc4_open: NetCDF: file not found
Error in ncdf4::nc_open(uri, verbose = T) : 
  Error in nc_open trying to open file https://dapds00.nci.org.au/thredds/catalog/gb6/BRAN/BRAN2020/annual/ocean_temp_ann_2005.nc (return_on_error= FALSE )

**Comment by btupper** [comment]
Hi,

You are very close!  AS I understand it you want to use the "dods" service. All of the services available can be listed (usually) using `Top$list_services()`.  It yields a list of bits of info about each service available.  In your case I see...

```
> Top$list_services()
$all
       name serviceType        base 
      "all"  "Compound"          "" 

$ncdods
             name       serviceType              base 
         "ncdods"         "OPENDAP" "/thredds/dodsC/" 

$HTTPServer
                  name            serviceType                   base 
          "HTTPServer"           "HTTPServer" "/thredds/fileServer/" 

$wms
           name     serviceType            base 
          "wms"           "WMS" "/thredds/wms/" 

$wcs
           name     serviceType            base 
          "wcs"           "WCS" "/thredds/wcs/" 

$subsetServer
                 name           serviceType                  base 
       "subsetServer"        "NetcdfSubset" "/thredds/ncss/grid/" 

$ncml
            name      serviceType             base 
          "ncml"           "NCML" "/thredds/ncml/" 

$uddc
            name      serviceType             base 
          "uddc"           "UDDC" "/thredds/uddc/" 

$iso
           name     serviceType            base 
          "iso"           "ISO" "/thredds/iso/" 
```

The (wonderful) ncdf4 package works with OPeNDAP.  So you want to use the "thredds/dodsC" path.  Like the following...

```
library(thredds)
top_uri <- 'https://dapds00.nci.org.au/thredds/catalog/gb6/BRAN/BRAN2020/catalog.xml'
Top <- thredds::CatalogNode$new(top_uri, prefix = "thredds")
services = Top$list_services()
L3 <- Top$get_catalogs("annual")
sst <- L3[[1]]$get_datasets("ocean_temp_ann_2004.nc")

base_uri <- paste0("https://dapds00.nci.org.au", services[["ncdods"]][["base"]])
uri <- paste0(base_uri, sst[["ocean_temp_ann_2004.nc"]]$url)
NC <- ncdf4::nc_open(uri)
```

Determining the `base_uri` always feels a bit hacky to me. Usually, I check the endpoint of the catalog to get the "data url" from the service page; like on [this page](https://dapds00.nci.org.au/thredds/dodsC/gb6/BRAN/BRAN2020/annual/ocean_temp_ann_2004.nc.html)  Once it is established it doesn't need to be checked again unless the provider changes the catalog or base url.

Does that resolve it for you?

**Comment by nhill917** [comment]
Thanks for the quick reply Ben, yes that resolved it. After much mucking
around, I figured out I could use the data url as well, but I prefer this
approach that I can code.

Thank you.
Kind regards,
Nick.

**Comment by btupper** [comment]
Yes, I agree it is easier (it appeals to my inner sloth).  But being able to navigate the catalog dynamically when the dataset updates is pretty darn wonderful, too.

**Comment by nhill917** [comment]
Sorry Ben, one other question. I can now successfully use nc_open() (and
read_ncdf()) to open an .nc file using the thredds link. But, what's the
easiest way to save/download that file locally? Ideally I'd like to read
in the nc file, subset it and then save it locally. save() does not work
for .nc files and using nc_create or similar seems a very long process to
save a file already in the desired .nc format...


Cheers,
Nick.

**Comment by btupper** [comment]
No worries.  It is an all too common issue many of us face.  Unfortunately, it is an unrelated issue.  This package is implemented just to help you find opendap (or other) services, not interact with them.

That said there are lots of examples on how to do just as you describe; in fact at our lab we do that all of the time.  See a package like [oisster](https://github.com/BigelowLab/oisster) as an example, but there are others like [obpg](https://github.com/BigelowLab/obpg) and [nbs](https://github.com/BigelowLab/nbs).  Our own workflow is to subset and save each slice as a single layer geotiff.  We are a relatively small shop and this model works well for us.

Also, I should point out that the [bowerbird](https://docs.ropensci.org/bowerbird/) package is designed in a similar way. I haven't used it but have always wanted to give it a go. 

If you have any troubles with the examples please feel free to post on [r-sig-geo mailing list](https://www.r-project.org/mail.html) with general questions (which I highly recommend subscribing to - it's not high traffic but I always learn new things from the discussions there.)  Or if it is a question specific to those datasets/paxckages then posting a github issue for those packages is the way to go.

**Comment by nhill917** [comment]
Much appreciated Ben. I agree the bowerbird package looks great and so did
a couple of the others you provided.

I have found the thredds package and its function tds_ncss_download() that
saves netcdf directly to file and you can give it a st_bbox arg to trim to
your preferred xy coords. https://github.com/mt-climate-office/thredds

Cheers,
Nick.

**Comment by btupper** [comment]
Oh, that looks nice!
